### ISSUE TITLE
Add new level 4 data to remotesensingdata.gov.scot - Pete/Matt

### ISSUE THREAD

**Issue by jonparsonsjncc** [jncc/scottish-lidar#27]
**Prerequisites**
- [x] Access to the data in a location appropriate to process it

**Assumptions**
- [x] Any issues found in the data should be highlighted and reported rather than fixed

**Product breakdown structure**
- [ ] An updated website displaying the additional level 4 data - on beta prior to going to live

**Work breakdown structure**
- [x] Sense check of data (Kostas Sideris)
- [x] Geoserver data prep (Kostas Sideris)
- [x] Geserver rebuild / expansion (Matt Debont, demoing to Pete)
- [ ] Geoserver data loading (Matt Debont, demoing to Kostas and Pete) (Geoserver web interface, similar to existing)
- [ ] Beta environment load (Pete) [2-4 days]
- [ ] Live environment load (Pete) [1-2 days]

- [ ] Resolve downloads which are still linking to https://s3-eu-west-1.amazonaws.com/scotland-gov-lidar/phase-2/dtm/27700/gridded/NO78_1M_DTM_PHASE2.tif
- [x] Provide overall data sizes for each file format in each level - so we can estimate egress costs for future bulk downloads

**Time code**
P315

**Comment by Kostassan** [comment]
Completed the check for the DTM. It seems there are some kind of "holes" in the data
