### ISSUE TITLE
Implement Civic cookie management - Pete

### ISSUE THREAD

**Issue by jonparsonsjncc** [jncc/scottish-lidar#31]
**Prerequisites**
- [x] Paid licence and an online account with Civic
- [ ] Cookie audit conducted to detail and classify each cookie
- [ ] An updated privacy policy

**Assumptions**
- [ ] New approach to cookie management has been piloted and checked by DEFRA on Scottish lidar website first

**Product breakdown structure**
- [ ] Cookie approach to be applied to jncc.gov.uk, sac.jncc.gov.uk, mhc.jncc.gov.uk, hub.jncc.gov.uk, data.jncc.gov.uk and mnr.jncc.gov.uk
- [ ] New privacy and cookie policies applied to jncc.gov.uk, sac.jncc.gov.uk, mhc.jncc.gov.uk, hub.jncc.gov.uk, data.jncc.gov.uk and mnr.jncc.gov.uk

**Work breakdown structure**
- [ ] ???

**Notes**
We have a paid licence with an api key c21c48ca8bb88a6c190b5cb444772f1970eb87ef 
You can use your email address and API key to login to the Cookie Control configuration page at any time: https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.civicuk.com%2Fcookie-control%2Flogin&amp;data=02%7C01%7CScottishRemoteSensingPortal%40jncc.gov.uk%7Cbfb1fd26747e4fcfcddf08d849d66462%7C444ee4e8b2fd491d8c318b0508370a6b%7C0%7C1%7C637340532448367737&amp;sdata=M0qvdUk8OzMiXmtzLdGoyJeuW%2BrK3ckcCZ3U%2Fknoiyg%3D&amp;reserved=0
Admin details for the civic website are stored within KeePass

**Time code**
p315a
