### ISSUE TITLE
Add Outer Hebrides data - Matt

### ISSUE THREAD

**Issue by jonparsonsjncc** [jncc/scottish-lidar#33]
MD can do:

- [ ] Sense check of data
- [ ] Geoserver data prep

PM can do: 
- [ ] DON'T FORGET! Resolve downloads which are still linking to https://s3-eu-west-1.amazonaws.com/scotland-gov-lidar/phase-2/dtm/27700/gridded/NO78_1M_DTM_PHASE2.tif
- [ ] Geoserver data loading
- [ ] Beta environment load
- [ ] Live environment load

See update from Kostas below

I did not have the chance to complete the Lidar prep work.
What I got this far is the Outer Hebrides mosaic for the DTM but not for the DSM as I mentioned earlier that the result was corrupted and
not viewable.
The next steps is to collate a DSM mosaic and after checking both to create from these the tiles that are required for the Geoserver output.
All  the files are located here : 
Scottish_Lidar_Level4\Outer_Hebrides 
jncc-it01
I have left also the corrupted file there just so the devs can see it.
